package lickpool.DatabaseConfig;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "lickpool_lickbanker")
public class LickPoolConfig {
    private String id = "config";
    private String startDate;
    private int iteration;
    private List leavers = new ArrayList<>();
    private BigDecimal bettingAmount;

    public LickPoolConfig() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @DynamoDBAttribute
    public int getIteration() {
        return iteration;
    }

    public void setIteration(int iteration) {
        this.iteration = iteration;
    }

    @DynamoDBAttribute
    public List<String> getLeavers() {
        return leavers;
    }

    public void setLeavers(List<String> leavers) {
        this.leavers = leavers;
    }

    @DynamoDBAttribute
    public BigDecimal getBettingAmount() {
        return bettingAmount;
    }

    public void setBettingAmount(BigDecimal bettingAmount) {
        this.bettingAmount = bettingAmount;
    }
}
